spring:
  redis:
    host: 192.168.77.131
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5
